#!/bin/bash
# -----------------------------------------------------------------------------
#
# This file is the copyrighted property of Tableau Software and is protected
# by registered patents and other applicable U.S. and international laws and
# regulations.
#
# Unlicensed use of the contents of this file is prohibited. Please refer to
# the NOTICES.txt file for further details.
#
# -----------------------------------------------------------------------------

#check if the job is running and should report if it is so
tsm jobs list --status Running | grep -E "InitializeServerJob" > /dev/null 2>&1
result=$?
if [ "${result}" -eq 0 ]; then
	echo "InitializeServerJob Running"
    exit 1
fi

#Initialization is finished so we can trust the server status report
tsm status | grep -E "RUNNING"
